In [1]:
import pandas as pd
data = pd.read_json('molecules.json').sample(1000)

data

                                                      xyz   u0_atom
125006  16\nH7 C5 N3 O1\nC 0.031346 1.591955 -0.167684... -2.502065
127319  14\nH5 C5 N3 O1\nO 0.026125 -0.049512 0.002344... -2.378692
26911   16\nH7 C5 N3 O1\nN 0.038865 1.395655 0.172195\... -2.595583
83322   19\nH10 C6 O3\nC 0.110360 1.564887 -0.267617\n... -2.959703
118795  20\nH11 C7 N1 O1\nC -0.230275 1.615134 0.16220... -3.096053
...                                                   ...       ...
1594    17\nH10 C5 O2\nC -0.082435 1.591861 -0.085419\... -2.512682
123711  21\nH12 C7 N2\nC 0.009765 1.509764 0.037506\nC... -3.211540
60114   19\nH10 C6 O3\nO -0.477144 0.976495 -0.336795\... -2.885689
119230  24\nH15 C7 N1 O1\nC -0.152504 1.223168 0.14988... -3.432392
35836   17\nH8 C6 O3\nC 0.020760 1.457953 0.038282\nC ... -2.652491

[1000 rows x 2 columns]